print("m.arsya")
print("m.arsya")
print("m.arsya rifqi")
print("m.arsya rifqi maulana")
print("m.arsya rifqi maulana anwar")
print("arsya arsya")
print("rifqi rifqi")
print("maulana maulana")
print("anwar anwar")
print("arsya")